# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        touch .env
        echo CELO_MAINNET_ADDRESS=${{secrets.CELO_MAINNET_ADDRESS}} >> .env
        echo HTTPS_GRAPHQL=${{secrets.HTTPS_GRAPHQL}} >> .env
        echo MATOMO_URL=${{secrets.MATOMO_URL}} >> .env
        echo WSS_GRAPHQL=${{secrets.WSS_GRAPHQL}} >> .env
        echo CELO_FRACTION=${{secrets.CELO_FRACTION}} >> .env
        echo WEBSITE_URL=${{secrets.WEBSITE_URL}} >> .env
        echo SET_PAGE=${{secrets.SET_PAGE}} >> .env
        echo PAGE_SIZE=${{secrets.PAGE_SIZE}} >> .env
        echo ROW_XXSMALL=${{secrets.ROW_XXSMALL}} >> .env
        echo ROW_XSMALL=${{secrets.ROW_XSMALL}} >> .env
        echo ROW_SMALL=${{secrets.ROW_SMALL}} >> .env
        echo ROW_MEDIUM=${{secrets.ROW_MEDIUM}} >> .env
        echo ROW_LARGE=${{secrets.ROW_LARGE}} >> .env
        echo ROW_XLARGE=${{secrets.ROW_XLARGE}} >> .env
        cat .env
    - run: npm install
    - run: npm run build-fragment 
    - run: npm run build-possible-types
    - run: npm run build --if-present
    - run: pm2 reload www.celo.bigdipper.live
      env:
        CI: true
